### ISSUE TITLE
Better support for milli/micro/nanosecond level conversion

### ISSUE THREAD

**Issue by saatvikshah** [snooze92/alfred-epoch-converter#2]
Thanks for writing this wonderful workflow - its very handy!

Currently, if I type `ts` it correctly gives me the timestamps in all units till nanoseconds. However if I instead type `ts 10:45:50.12` or `ts 2020-12-08 10:45:50.12` it only shows the unix timestamp corresponding to `<local date> 10:45:50` ignoring the `.12` or related smaller unit. 

This can also be seen in the text below that shows `local (us/ms/ns) epoch for <local date>  10:45:50`.
![image](https://user-images.githubusercontent.com/6854735/101543245-96d7b380-3969-11eb-9787-8e76b3ef0c65.png)

How difficult might it be to add support for this?

**Comment by snooze92** [comment]
It's pretty straightforward to make your example work:
![subseconds](https://user-images.githubusercontent.com/3275550/101844209-30f75180-3b4c-11eb-87a3-1efc21581794.png)

It works all the way down to microseconds:
![microseconds](https://user-images.githubusercontent.com/3275550/101844320-6c921b80-3b4c-11eb-9164-8742588246dd.png)

It does not work with nanoseconds, because Python's [`strftime`](https://strftime.org/) uses `%f` to represent microseconds. I think I prefer accepting that limitation, rather than trying to complicate things and work around `strftime`.

I assume that is acceptable, because the workflow to convert would be:
- convert the second timestamp
- type the 9 digits of nanosecond behind it after pasting

That really isn't too much worse than if we supported:
- type the 9 digits of nanosecond before converting
- convert the nanosecond tiemstamp

I'll commit a change shortly!

**Comment by snooze92** [comment]
[Released](https://github.com/snooze92/alfred-epoch-converter/releases) in `1.0.1`, [in Packal](http://www.packal.org/workflow/epoch-converter-0) as well.
