### ISSUE TITLE
human-readable conversion seems to be broken for 1.0.1

### ISSUE THREAD

**Issue by yvkg** [snooze92/alfred-epoch-converter#7]
Works on 1.0.0 but not on the latest version.
![Screen Shot 2021-12-22 at 8 56 43 AM](https://user-images.githubusercontent.com/59266375/147128129-8f8f5f8a-8d2e-4872-a9eb-9b79b5ed21b2.png)

**Comment by habond** [comment]
+1

**Comment by snooze92** [comment]
Thanks for reporting! I was unable to reproduce at first, but that's because I use the latest commit from the repository, instead of the latest explicit release. Checking the "old" `1.0.1` release, I now see the same issue. Apologies for not releasing explicitly sooner!

I fixed something unrelated and released `1.0.2` now; can you confirm that everything works for you in `1.0.2`?

**Comment by habond** [comment]
@snooze92 works great with 1.0.2, thank you!
